ETH = {
    "data_paths": "data/raw/pedestrians/ETH",
    "save_path": "data/processed/all_pedestrian_trajectories_ETH.npy",
    "processed_path": "data/processed/ETH.pt",
    "weights_path": "final_weights/ETH-UCY/ETH-0_weights.pth",  # CHANGE THIS TO CORRESPONDING DATASET
    "type": 0,  # CHANGE THIS TO CORRESPONDING DATASET 0 = ETH, 1 = Hotel, 2 = Zara 01, 3 = Zara 02, 4 = Univ
    "preprocess_frequency": 1,
    "preprocess_outlier_zscore_threshold": 4.0,
    "preprocess_fraction_of_length": 1.0,
    "preprocess_sliding_window_step": 1,
    "preprocess_nans_in_trajectory_threshold": 0.0,
    "dims": 2,
    "time_window": 20,
    "cond_frames": 8,
    "give_last_frame": True,
    "knn": 10,  # HYPERPARAMETER FROM APPENDIX, connectivity k
    "radius_graph": 8,  # HYPERPARAMETER FROM APPENDIX , connectivity r
    "min_velocity_filter": 0.0,
    "min_num_trajs_filter": 1,
    "max_x_and_y": 25.0,
    "x_range": (-15, 15),
    "y_range": (-15, 15),
    "augmentations": ["rotate"] * 2,  # HYPERPARAMETER FROM APPENDIX
    "max_samples": 20_000,
    "temporal_edges": (0, 0),
    "node_features": {
        "x": 2,
        "y": 3,
        "vel_x": 0,
        "vel_y": 1,
        "velocity_magnitude": 4,
        "acceleration_x": 5,
        "acceleration_y": 6,
        "acceleration_magnitude": 7,
        "local_density": 8,
    },
    "edge_features": {
        "euclidean_dist": 0,
        "relative_turning_angle": 3,
        "delta_x": 1,
        "delta_y": 2,
        "delta_vel_x": 4,
        "delta_vel_y": 5,
        "relative_density": 6,
    },  # Edge features and indices
    "dist_kernel": 1.0,
    "use_dynamic_edges": True,
    "use_optimal_transport": False,
    "use_two_stage_approach": False,
    "use_split_approach": True,
    "model_layers": [
        "MP",
        "UNet",
    ],  # HYPERPARAMETER FROM APPENDIX, ["MP", "UNet"] = 1 layer, ["MP", "UNet", "MP", "UNet"] = 2 layers
    "use_edge_mlp": False,
    "model_path": "checkpoints",
    "use_inpainting_mask": True,
    "use_uniform_mask": False,  # uniformly sample size of mask
    "predict_velocity": True,
    "predict_acceleration": False,
    "fm_sigma": 0.00,
    "t_sample_dist": 0.5,  # HYPERPARAMETER FROM APPENDIX, tau disitrbution, 1 = uniform, 0.5 = square root
    "prior_type": "informed_walk",
    "prior_gauss_std": 1.0,
    "prior_noise_factor": 4,  # HYPERPARAMETER FROM APPENDIX, s
    "inference_prior_noise_factor": 4,  # HYPERPARAMETER FROM APPENDIX, s
    "loss_functions": {"mse": 1.0, "relative_position": 0.00, "collision": 0.0},
    "learning_rate": 5e-4,  # HYPERPARAMETER FROM APPENDIX, lr
    "epochs": 100,  # HYPERPARAMETER FROM APPENDIX, epochs
    "hidden_dim": 64,
    "val_split": 0.15,  # HYPERPARAMETER FROM APPENDIX, val split
    "test_split": 0.1,  # Irrelevant for ETH-UCY, hold-one-out strategy is used
    "batch_size": 32,  # HYPERPARAMETER FROM APPENDIX, batch size
    "test_size": 5000,
    "use_best_of_20": True,
    "use_mean_of_5": False,
    "val_rollouts": 1,
    "use_fp16": False,
    "dropout": 0.00,
    "adaptive_solver": None,
    "nfe": 50,
}

NBODY = {
    "data_paths": "data/raw/nbody",
    "save_path": "data/processed/all_trajectories_nbody.npy",
    "processed_path": "data/processed/nbody.pt",
    "weights_path": "final_weights/NBody/NBody-gravity_weights.pth",  # CHANGE THIS TO CORRESPONDING DATASET
    "type": "gravity",  # charged, gravity or springs  CHANGE THIS TO CORRESPONDING DATASET
    "dims": 3,
    "time_window": 30,
    "cond_frames": 10,
    "give_last_frame": True,
    "knn": 10,
    "radius_graph": None,
    "min_velocity_filter": 0.0,
    "min_num_trajs_filter": 1,
    "max_x_and_y": 25.0,
    "x_range": (-5, 5),
    "y_range": (-5, 5),
    "z_range": (-5, 5),
    "augmentations": ["rotate"] * 8,
    "max_samples": 30_000,
    "temporal_edges": (0, 0),
    "node_features": {
        "x": 3,
        "y": 4,
        "z": 5,
        "vel_x": 0,
        "vel_y": 1,
        "vel_z": 2,
        "velocity_magnitude": 6,
        "acceleration_x": 7,
        "acceleration_y": 8,
        "acceleration_z": 9,
        "acceleration_magnitude": 10,
        # "charge": 11,                    # UNCOMMENT IF DATASET IS CHARGED
    },
    "edge_features": {
        "euclidean_dist": 0,
        "delta_x": 1,
        "delta_y": 2,
        "delta_z": 3,
        "delta_vel_x": 4,
        "delta_vel_y": 5,
        "delta_vel_z": 6,
        # "spring": 7,                   # UNCOMMENT IF DATASET IS SPRINGS
    },  # Edge features and indices
    "dist_kernel": 1.0,  # Gaussian kernel sigma for densities in m
    "use_dynamic_edges": True,
    "use_optimal_transport": False,
    "use_two_stage_approach": False,
    "use_split_approach": True,
    "model_layers": [
        "MP",
        "UNet",
        "MP",
        "UNet",
        "MP",
        "UNet",
    ],  # HYPERPARAMETER FROM APPENDIX, ["MP", "UNet"] = 1 layer, ["MP", "UNet", "MP", "UNet"] = 2 layers
    "use_edge_mlp": False,
    "model_path": "checkpoints",
    "use_inpainting_mask": True,
    "use_uniform_mask": False,
    "predict_velocity": True,
    "predict_acceleration": False,
    "fm_sigma": 0.00,
    "t_sample_dist": 0.5,  # HYPERPARAMETER FROM APPENDIX, tau disitrbution, 1 = uniform, 0.5 = square root
    "prior_type": "informed_walk",  # informed_wal, full gaussian or position gaussian
    "prior_gauss_std": 0.5,
    "prior_noise_factor": 4,  # HYPERPARAMETER FROM APPENDIX, s
    "inference_prior_noise_factor": 4,  # HYPERPARAMETER FROM APPENDIX, s
    "loss_functions": {"mse": 1.0, "relative_position": 0.00, "collision": 0.0},
    "learning_rate": 5e-4,  # HYPERPARAMETER FROM APPENDIX, lr
    "epochs": 200,  # HYPERPARAMETER FROM APPENDIX, epochs
    "hidden_dim": 64,
    "val_split": 0.15,  # HYPERPARAMETER FROM APPENDIX,
    "test_split": 0.15,  # HYPERPARAMETER FROM APPENDIX,
    "batch_size": 32,  # HYPERPARAMETER FROM APPENDIX,
    "test_size": 5000,
    "use_best_of_20": False,
    "use_mean_of_5": True,
    "val_rollouts": 1,
    "adaptive_solver": None,
    "use_fp16": False,
    "dropout": 0.00,
    "nfe": 50,
}

MD17 = {
    "data_paths": "data/raw/md17",
    "save_path": "data/processed/all_trajectories_md17.npy",
    "processed_path": "data/processed/md17.pt",
    "weights_path": "final_weights/MD17/MD17-ethanol_weights.pth",
    "type": "ethanol",
    "dims": 3,
    "time_window": 30,
    "cond_frames": 10,
    "give_last_frame": True,
    "knn": 22,
    "radius_graph": None,
    "min_velocity_filter": 0.0,
    "min_num_trajs_filter": 1,
    "max_x_and_y": 25.0,
    "x_range": (-5, 5),
    "y_range": (-5, 5),
    "z_range": (-5, 5),
    "augmentations": ["rotate"] * 8,  # HYPERPARAMETER FROM APPENDIX
    "max_samples": 30_000,
    "temporal_edges": (0, 0),
    "node_features": {
        "atom_0": 0,
        "atom_1": 1,
        "atom_2": 2,
        "atom_3": 3,
        "atom_4": 4,
        "atom_5": 5,
        "atom_6": 6,
        "atom_7": 7,
        "atom_8": 8,
        "atom_9": 9,
        "x": 10,
        "y": 11,
        "z": 12,
        "vel_x": 13,
        "vel_y": 14,
        "vel_z": 15,
        "velocity_magnitude": 16,
        "acceleration_x": 17,
        "acceleration_y": 18,
        "acceleration_z": 19,
        "acceleration_magnitude": 20,
    },
    "edge_features": {
        "euclidean_dist": 0,
        "delta_x": 1,
        "delta_y": 2,
        "delta_z": 3,
        "delta_vel_x": 4,
        "delta_vel_y": 5,
        "delta_vel_z": 6,
    },  # Edge features and indices
    "dist_kernel": 1.0,
    "use_dynamic_edges": True,
    "use_optimal_transport": False,
    "use_two_stage_approach": False,
    "use_split_approach": True,
    "model_layers": ["MP", "UNet", "MP", "UNet", "MP", "UNet"],
    "use_edge_mlp": False,
    "model_path": "checkpoints",
    "use_inpainting_mask": True,
    "use_uniform_mask": False,
    "predict_velocity": True,
    "predict_acceleration": False,
    "fm_sigma": 0.00,
    "t_sample_dist": 0.5,
    "prior_type": "informed_walk",
    "prior_gauss_std": 1.0,
    "prior_noise_factor": 4,
    "inference_prior_noise_factor": 4,
    "loss_functions": {"mse": 1.0, "relative_position": 0.00, "collision": 0.0},
    "learning_rate": 5e-4,
    "epochs": 300,
    "hidden_dim": 64,
    "val_split": 0.15,
    "test_split": 0.15,
    "batch_size": 32,
    "test_size": 50,
    "use_best_of_20": False,
    "use_mean_of_5": True,
    "adaptive_solver": None,
    "val_rollouts": 1,
    "use_fp16": False,
    "dropout": 0.00,
    "nfe": 50,
}
